# database to store all figure information
figures:
  - title: Template
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/template.png
    url_paper: ~
    # url_src: https://share.weiyun.com/v1odzL0k
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/template.pptx
    url_project: ~
  - title: basic-neurons
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/basic_neurons.png
    url_paper: ~
    # url_src: https://share.weiyun.com/auh4XsFH
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/basic_neurons.pptx
    url_project: ~
  - title: GFPGAN-overvie
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/GFPGAN_overview.png
    url_paper: https://arxiv.org/abs/2101.04061
    # url_src: https://share.weiyun.com/auh4XsFH
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/GFPGAN_overview.pptx
    url_project: https://github.com/TencentARC/GFPGAN
  - title: GFPGAN-teaser
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/GFPGAN_teaser.jpg
    url_paper: https://arxiv.org/abs/2101.04061
    # url_src: https://share.weiyun.com/4r1KMeRr
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/GFPGAN_teaser.pptx
    url_project: https://github.com/TencentARC/GFPGAN
  - title: RealESRGAN-highorder
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/RealESRGAN_highorder.png
    url_paper: https://arxiv.org/abs/2107.10833
    # url_src: https://share.weiyun.com/OadwiOyB
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/RealESRGAN_highorder.pptx
    url_project: https://github.com/xinntao/Real-ESRGAN
  - title: RealESRGAN-teaser
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/RealESRGAN_teaser.jpg
    url_paper: https://arxiv.org/abs/2107.10833
    # url_src: https://share.weiyun.com/4r1KMeRr
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/RealESRGAN_teaser.pptx
    url_project: https://github.com/xinntao/Real-ESRGAN
  - title: RealESRGAN-network
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/RealESRGAN_network.jpg
    url_paper: https://arxiv.org/abs/2107.10833
    # url_src: https://share.weiyun.com/PWk5Lvjd
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/RealESRGAN_network.pptx
    url_project: https://github.com/xinntao/Real-ESRGAN
  - title: RealESRGAN-blur
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/RealESRGAN_blur.jpg
    url_paper: https://arxiv.org/abs/2107.10833
    # url_src: https://share.weiyun.com/LLBTT9vO
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/RealESRGAN_blur.pptx
    url_project: https://github.com/xinntao/Real-ESRGAN
  - title: FAIG-teaser
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/FAIG_teaser.jpg
    url_paper: https://openreview.net/pdf?id=az0BBDjDvwD
    # url_src: https://share.weiyun.com/wycZL7U6
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/FAIG_teaser.pptx
    url_project: https://github.com/TencentARC/FAIG
  - title: FAIG-motivation
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/FAIG_motivation.png
    url_paper: https://openreview.net/pdf?id=az0BBDjDvwD
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/FAIG_motivation.pptx
    url_project: https://github.com/TencentARC/FAIG
  - title: FAIG-compare
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/FAIG_compare.jpg
    url_paper: https://openreview.net/pdf?id=az0BBDjDvwD
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/FAIG_compare.pptx
    url_project: https://github.com/TencentARC/FAIG
  - title: Colorization
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/Colorization.png
    url_paper: https://arxiv.org/abs/2108.08826
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/Colorization.pptx
    url_project: ~
  - title: DNI-teaser
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/DNI_teaser.jpg
    url_paper: https://arxiv.org/abs/1811.10515
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/DNI_teaser.pptx
    url_project: https://xinntao.github.io/projects/DNI
  - title: EDVR-teaser
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/EDVR_teaser.jpg
    url_paper: https://arxiv.org/abs/1905.02716
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/EDVR_teaser.pptx
    url_project: https://xinntao.github.io/projects/EDVR
  - title: EDVR-network
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/EDVR_network.jpg
    url_paper: https://arxiv.org/abs/1905.02716
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/EDVR_network.pptx
    url_project: https://xinntao.github.io/projects/EDVR
  - title: EDVR-pcd-tsa
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/EDVR_pcd_tsa.png
    url_paper: https://arxiv.org/abs/1905.02716
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/EDVR_pcd_tsa.pptx
    url_project: https://xinntao.github.io/projects/EDVR
  - title: EDVR-ablation
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/EDVR_ablation.jpg
    url_paper: https://arxiv.org/abs/1905.02716
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/EDVR_ablation.pptx
    url_project: https://xinntao.github.io/projects/EDVR
  - title: ESRGAN-teaser
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/ESRGAN_teaser.jpg
    url_paper: https://arxiv.org/abs/1809.00219
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/ESRGAN_teaser.pptx
    url_project: https://github.com/xinntao/ESRGAN
  - title: ESRGAN-network
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/ESRGAN_network.png
    url_paper: https://arxiv.org/abs/1809.00219
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/ESRGAN_network.pptx
    url_project: https://github.com/xinntao/ESRGAN
  - title: SFTGAN-network
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/SFTGAN_network.png
    url_paper: https://arxiv.org/abs/1804.02815
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/SFTGAN_network.pptx
    url_project: http://mmlab.ie.cuhk.edu.hk/projects/SFTGAN/
  - title: SFTGAN-modulation
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/SFTGAN_modulation.jpg
    url_paper: https://arxiv.org/abs/1804.02815
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/SFTGAN_modulation.pptx
    url_project: http://mmlab.ie.cuhk.edu.hk/projects/SFTGAN/
  - title: UnderstandDCN-illustration
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/UnderstandDCN_illustration.png
    url_paper: https://arxiv.org/abs/2009.07265
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/UnderstandDCN_illustration.pptx
    url_project: ~
  - title: UnderstandDCN-network
    url_img: https://raw.githubusercontent.com/xinntao/HandyFigure/master/figures/UnderstandDCN_network.png
    url_paper: https://arxiv.org/abs/2009.07265
    url_src: https://github.com/xinntao/HandyFigure/releases/download/PPT-source/UnderstandDCN_network.pptx
    url_project: ~
